- packages/sdk/src/auth/interfaces/create-jwt.ts
The rest of the code is already compatible for an array of audiences
> minor audience field change

- CHANGELOG.md
- nx.json
- packages/sdk/package.json
As title says, very simple changes
> Updating Package Version + nx.json for Publishing

- packages/sdk/tsconfig.lib.json
Add a missing `tsconfig.lib.json` file forgotten to commit in this pr https://github.com/LIT-Protocol/Vincent/pull/20
> fix(build): add missing tsconfig.lib.json

- package.json
- packages/sdk/tsconfig.json
- pnpm-lock.yaml
Simple fixes to have the build succeed
> SDK Build fix

- packages/dashboard/app/[appId]/advanced-functions/page.tsx
- packages/dashboard/app/[appId]/delegatee/page.tsx
- packages/dashboard/app/[appId]/page.tsx
- packages/dashboard/app/[appId]/tool-policies/page.tsx
- packages/dashboard/app/create-app/page.tsx
- packages/dashboard/components/developer/Dashboard.tsx
- Adding new routes for each of the dashboard pages:
- Create App
- Advanced Functions
- Manage Delegatees
- Manage Tools + Policies
- App View
> Dashboard Routes

- packages/dashboard/components/developer/CreateApp.tsx
- Redirect to root dashboard after consenting
- Specific error message requiring 1+ `redirectUri`
> Minor fixes

- packages/dashboard/components/developer/CreateApp.tsx
Allow empty policies or policy parameters when registering the app
> Allow empty form fields

- packages/dashboard/app/create-app/page.tsx
- packages/dashboard/app/page.tsx
- packages/dashboard/components/consent/components/AuthenticatedConsentForm.tsx
- packages/dashboard/components/consent/components/authForm/AppInfo.tsx
- packages/dashboard/components/developer/CreateApp.tsx
- Forceful page reload upon successful app creation
- Small UI fixes
> Small Fixes

- packages/dashboard/components/consent/components/StytchOTP.tsx
- Add a login template for custom Stytch
> Add login template

- packages/dashboard/components/consent/components/AuthenticatedConsentForm.tsx
- packages/dashboard/components/consent/components/authForm/ParameterUpdateModal.tsx
- packages/dashboard/components/consent/components/authForm/VersionUpgradePrompt.tsx
- packages/dashboard/components/consent/hooks/useVersionEnabledCheck.ts
- packages/dashboard/components/consent/utils/consentVerificationUtils.ts
- packages/dashboard/components/developer/dashboard/ManageAdvancedFunctions.tsx
Adding warnings:
Styles may change soon if you think these are ugly, but the warning is needed.
> Consent Page Warnings for Disabled Versions

- packages/dashboard/components/consent/components/SessionValidator.tsx
> SessionValidator Console Logs

- package.json
- packages/sdk/package.json
- pnpm-lock.yaml
- Published @lit-protocol/vincent-sdk@0.0.6
- Includes JWT upgrades from #73
- Updated dashboard dependency to use the latest version
> Release V0.0.6

- packages/dashboard/components/consent/hooks/useJwtRedirect.ts
Fixes a reference in auth info params dereference
> fix: fix reference to auth info

- packages/sdk/typedoc.json
> fix(docs): rename (remove API)

- nx.json
- package.json
- packages/app-dashboard/package.json
- packages/app-dashboard/src/components/consent/components/authForm/ParameterInput.tsx
- packages/app-dashboard/src/services/contract/config.ts
- packages/app-dashboard/src/services/contract/contracts.ts
- packages/app-dashboard/src/utils/parameterEncoding.ts
- packages/mcp/package.json
- packages/mcp/project.json
- packages/mcp/tsconfig.json
- packages/sdk/package.json
- packages/sdk/project.json
- packages/sdk/src/jwt/types.ts
- packages/sdk/src/mcp/index.ts
- packages/vincent-tools/vincent-tool-sdk/.gitignore
- packages/vincent-tools/vincent-tool-sdk/jest.config.js
- packages/vincent-tools/vincent-tool-sdk/package.json
- packages/vincent-tools/vincent-tool-sdk/project.json
This PR:
1. Adds vincent-tool-sdk to the sdk (and more in main) release pipeline. First publishing was done already [here](https://www.npmjs.com/package/@lit-protocol/vincent-tool-sdk)
2. Fixes the incorrect bundling directory of `@lit-protocol/vincent-sdk`. Check that vincent sdk had [its files](https://www.npmjs.com/package/@lit-protocol/vincent-sdk?activeTab=code) in `/dist/src`, duplicating README.md and package.json. Now it will publish without the extra `dist` as the [tool sdk](https://www.npmjs.com/package/@lit-protocol/vincent-tool-sdk?activeTab=code) or the [mcp](https://www.npmjs.com/package/@lit-protocol/vincent-mcp?activeTab=code)
3. Changes the references between our pkgs (dashboard including sdk, mcp including mcp, etc.) that we had hardcoded in a version with `workspace:*`
> Add tool sdk to release pipeline and local pkg references

- packages/sdk/docs/Developers/App-Agent-Developers/Getting-Started.md
- packages/sdk/docs/Developers/Getting-Started.md
- packages/sdk/docs/Developers/Policy-Developers/Creating-Policies.md
- packages/sdk/docs/Developers/Tool-Developers/Creating-Tools.md
> Add link to DCA demo repo, and rename `Tool & Policy SDK` to `Tool SDK`

- docs/src/Developers/Policy-Developers/Creating-Policies.md
> chore: Remove merge conflict marker

- typedoc.site.config.js
- docs: Fix readme should load from `Why-Vincent.md`
> docs: Fix readme should load from `Why-Vincent.md`

- docs/src/Developers/App-Agent-Developers/Creating-Apps.md
- docs/src/Why-Vincent.md
Remove "alpha" warning from the Docs
> feat: Remove alpha warning from docs

- .nx/version-plans/version-plan-1752159560402.md
- packages/apps/registry-backend/CHANGELOG.md
- packages/apps/registry-backend/package.json
- packages/apps/registry-backend/src/lib/express/app/routes.ts
- packages/apps/registry-backend/src/lib/mongo/app.ts
- packages/apps/registry-backend/test/integration/app.spec.ts
- packages/libs/registry-sdk/CHANGELOG.md
- packages/libs/registry-sdk/package.json
- packages/libs/registry-sdk/src/generated/openapi.json
- packages/libs/registry-sdk/src/generated/vincentApiClientNode.ts
- packages/libs/registry-sdk/src/generated/vincentApiClientReact.ts
- packages/libs/registry-sdk/src/lib/schemas/app.ts
Added arrays of `delegateeAddresses` to the `app` doc, as well as its creation and editing.
> Add delegateeAddresses to Apps in the Registry

- packages/libs/contracts-sdk/src/facets/User.ts
> fix(contracts-sdk): Fix incorrect function signature for `encodePermssionDataForChain()`

- .nx/version-plans/version-plan-1753317614614.md
- .nx/version-plans/version-plan-1753317614620.md
- packages/apps/registry-backend/src/lib/express/policy/routes.ts
- packages/apps/registry-backend/src/lib/express/tool/routes.ts
- packages/apps/registry-backend/src/lib/mongo/policy.ts
- packages/apps/registry-backend/src/lib/mongo/tool.ts
- packages/apps/registry-backend/test/integration/app.spec.ts
- packages/apps/registry-backend/test/integration/appVersionTool.spec.ts
- packages/apps/registry-backend/test/integration/authorization.spec.ts
- packages/apps/registry-backend/test/integration/policy.spec.ts
- packages/apps/registry-backend/test/integration/tool.spec.ts
- packages/libs/registry-sdk/src/generated/openapi.json
- packages/libs/registry-sdk/src/generated/vincentApiClientNode.ts
- packages/libs/registry-sdk/src/generated/vincentApiClientReact.ts
- packages/libs/registry-sdk/src/lib/schemas/policy.ts
- packages/libs/registry-sdk/src/lib/schemas/tool.ts
- Added logos to tools and policies
- Fixed failing e2e tests due to the bump of the `vincent-contracts-sdk`
Passes e2e tests and the new `logo` property is visible in the deployed `api.html`, and successfully created tools + policies with logos on local dev
> feat(registry-sdk + registry-backend): tool + policy logos

- docs/src/Concepts.md
- docs/src/Users/Introduction.md
- typedoc.site.config.js
introduced an "intro" page for the user docs and simplified the "key concepts" section
> user docs edits

- packages/libs/contracts-sdk/contracts/IPKPNftFacet.sol
Remove mention of `tool` from comment in packages/libs/contracts-sdk/contracts/IPKPNftFacet.sol
> fix: remove tool from comment

- docs/custom.css
Simple css fix for the docs.
Before:
After:
> chore(docs): fix nested accordion margin

- packages/apps/app-dashboard/index.html
- packages/apps/app-dashboard/package.json
- packages/libs/app-sdk/src/jwt/core/utils/verifyES256KSignature.ts
- pnpm-lock.yaml
Fix `app-sdk` arrayify to add `0x` prefix if it doesn't exist on public key, fix favicon.
> fix(dashboard): fix app-sdk, favicon

- packages/libs/app-sdk/docs/json
- packages/libs/app-sdk/src/jwt/core/create.ts
Updated typedoc verbiage per PR feedback on https://github.com/LIT-Protocol/Vincent/pull/241
> chore(app-sdk): JWT doc follow-up

- packages/apps/app-dashboard/src/hooks/developer-dashboard/useVincentApiWithJWT.ts
Simple fix, as title says.
Locally + preview
> fix(dashboard): remove https from JWT expected audience

- .nx/version-plans/version-plan-1755273102245.md
- packages/apps/registry-backend/CHANGELOG.md
- packages/libs/registry-sdk/CHANGELOG.md
- project: registry-sdk 4.1.0
- project: registry-backend 2.1.0
Updated changelogs, pushed tags
😢
> chore(release): Publish registry-sdk and registry-backend

- packages/apps/app-dashboard/src/components/developer-dashboard/sidebar/DeveloperSidebarError.tsx
- packages/apps/app-dashboard/src/components/shared/AccountTooltip.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/ConnectPageHeader.tsx
Just remove it from tooltips and headers.
> chore(dashboard): remove userPKP.ethAddress from being shown anywhere

- .nx/version-plans/version-plan-1755533774990.md
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ConnectPage.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/AbilityAccordion.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/AppInfo.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/PolicyForm.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/RequiredPolicies.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/dashboard/UpdateVersionPage.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/dashboard/UserPermissionPage.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/dashboard/ui/PermittedAppInfo.tsx
- packages/apps/app-dashboard/src/hooks/user-dashboard/connect/useCanGoBack.ts
- packages/apps/app-dashboard/src/hooks/user-dashboard/connect/useConnectFormData.ts
- packages/apps/app-dashboard/src/hooks/user-dashboard/dashboard/useFormatUserPermissions.ts
- packages/libs/contracts-sdk/jest.config.js
- packages/libs/contracts-sdk/src/internal/user/User.ts
- packages/libs/contracts-sdk/src/types.ts
- packages/libs/contracts-sdk/src/utils/policyParams.ts
- packages/libs/contracts-sdk/test/policyParams.spec.ts
Adds optional policies to the connect page:
- Policy isn't selected = IPFS and policy parameters aren't in the encoded data
- Policy selected, fields empty = IPFS in encoded data, parameters encoded with the values as undefined
- Fields are only empty if the policy allows it. Otherwise the validation just fails
- Policy selected, partially empty = IPFS in encoded data, empty fields still undefined
Locally with all of the cases above
> feat(dashboard): optional policies

- packages/apps/app-dashboard/src/components/user-dashboard/connect/ConnectPage.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/StatusCard.tsx
- packages/apps/app-dashboard/src/hooks/user-dashboard/connect/useAddPermittedActions.ts
- packages/apps/app-dashboard/src/utils/user-dashboard/lit.ts
Adds logging and a retry mechanism for adding payees. Works in sentry:
Locally in the development Sentry project.
> fix(dashboard): properly log errors in sentry, add retry mechanism

- packages/apps/app-dashboard/src/components/developer-dashboard/sidebar/Sidebar.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/auth/EthWalletAuth.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/Connect.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/ConnectPageHeader.tsx
- packages/apps/app-dashboard/src/components/user-dashboard/sidebar/AppSidebar.tsx
- packages/apps/app-dashboard/src/hooks/user-dashboard/useAuthInfo.ts
Improves the dashboard authentication states:
- Sentry logging. Errors fail gracefully, but we will be informed.
- Events + listeners to inform our components of authentication instead of forcing a hard refresh with `window.location.refresh`
- Improves loading speed since we don't need to initialize the providers when users sign in/out.
- Updates authentication states across tabs!
Local dev and Sentry testing with our development dashboard project.
> chore(dashboard): improved authentication states

- packages/apps/app-dashboard/src/hooks/user-dashboard/WalletConnect/useWalletConnectSession.ts
Bug fix, reset the agent PKP signer when the selected address changes.
Local dev
> fix(dashboard): Reset walletRegistered when agentPKP changes

- packages/apps/app-dashboard/src/components/user-dashboard/auth/EthWalletAuth.tsx
- packages/apps/app-dashboard/src/hooks/user-dashboard/WalletConnect/useWalletConnectRequests.ts
Simple fix, use v6 when estimating gas for transactions proposed by WalletConnect.
Withdrawing from Morpho, comparing with previous gas expense
> fix(dashboard): use ethers v6 gas estimation

- packages/apps/app-dashboard/src/components/developer-dashboard/app/views/AppDetailsView.tsx
- packages/apps/app-dashboard/src/components/developer-dashboard/app/wrappers/AppVersionAbilitiesWrapper.tsx
> chore(dashboard): copy button under app name, publish CTA

- packages/apps/app-dashboard/src/pages/shared/RootPage.tsx
Small update, just makes the logo size on the root page more reasonable.
Locally
> chore(dashboard): smaller mobile RootPage logo size
