packages/sdk/package.json

Another missing piece to remove from rollup to nx default settings from https://github.com/LIT-Protocol/Vincent/pull/20

fix(sdk): package.json exports

---

packages/sdk/package.json
packages/sdk/src/app/app.ts
packages/sdk/tsconfig.json
pnpm-lock.yaml

- Module to `nodenext`
- Added explicit tslib dep
- Modified package.json to ensure build is correct and 'types' is referenced correctly
Fixes issue w/ dca-backend in Heroku

build(vincent-sdk): Fix vincent-sdk build for modern NodeJS

---

packages/dashboard/app/appId/[appId]/page.tsx
packages/dashboard/components/developer/dashboard/AppUrlGenerator.tsx
packages/dashboard/components/developer/dashboard/ManageToolPolicies.tsx

- Added a button to generate an application URL using a choice of the `authorizedRedirectUris` (images below)
- Minor improvements to the "Manage Tool Policies" page

URL Creation Button + Dashboard UI Improvements

---

.nx/version-plans/version-plan-1749960117243.md
packages/sdk/docs/src/css/custom.css

Styling for info boxes when using darkmode

---

packages/libs/tool-sdk/docs/json
packages/libs/tool-sdk/src/index.ts
packages/libs/tool-sdk/src/lib/handlers/vincentPolicyHandler.ts
packages/libs/tool-sdk/src/lib/handlers/vincentToolHandler.ts
packages/libs/tool-sdk/src/lib/policyCore/bundledPolicy/bundledPolicy.ts
packages/libs/tool-sdk/src/lib/policyCore/bundledPolicy/types.ts
packages/libs/tool-sdk/src/lib/policyCore/policyDef/context/types.ts
packages/libs/tool-sdk/src/lib/policyCore/policyDef/types.ts
packages/libs/tool-sdk/src/lib/policyCore/vincentPolicy.ts
packages/libs/tool-sdk/src/lib/toolCore/bundledTool/bundledTool.ts
packages/libs/tool-sdk/src/lib/toolCore/bundledTool/types.ts
packages/libs/tool-sdk/src/lib/toolCore/helpers/supportedPoliciesForTool.ts
packages/libs/tool-sdk/src/lib/toolCore/toolDef/context/types.ts
packages/libs/tool-sdk/src/lib/toolCore/toolDef/types.ts
packages/libs/tool-sdk/src/lib/toolCore/vincentTool.ts
packages/libs/tool-sdk/src/lib/types.ts
packages/libs/tool-sdk/typedoc-configs/base.config.js

Just some docs updates for clarity, to reduce verbosity, and grouping the docs together by API methods vs. interfaces

docs: Update tools-sdk doc output to be less verbose and clarify some content

---

README.md

- Fix README links to reference `docs.heyvincent.ai` instead of our Vercel deployment URL

docs: Fix README links domain

---

docs/custom.css
docs/src/Developers/App-Agent-Developers/Creating-Apps.md
docs/src/Developers/App-Agent-Developers/Executing-Tools.md
docs/src/Developers/App-Agent-Developers/Upgrading-Apps.md
docs/src/Why-Vincent.md

Add the following warning to the doc pages:
- Why Vincent (homepage)
- Creating Vincent Apps
- Also removes the previous fix for OS color theme preference as having light mode selected for OS broke the styling for dark theme. I don't think there's a proper fix for this, and users should just select the theme they want to use and the OS theme option might be broken for them

Add `Vincent is in Alpha` warning

---

.nx/version-plans/version-plan-1750809053574.md
.nx/version-plans/version-plan-1750809155512.md
nx.json
package.json
packages/apps/app-dashboard/package.json
packages/apps/registry-backend/CHANGELOG.md
packages/apps/registry-backend/package.json
packages/apps/registry-backend/src/lib/express/app/requireAppTool.ts
packages/apps/registry-backend/src/lib/express/app/requireAppVersion.ts
packages/apps/registry-backend/src/lib/express/app/routes.ts
packages/apps/registry-backend/src/lib/mongo/app.ts
packages/apps/registry-backend/test/integration/appVersionTool.spec.ts
packages/apps/registry-backend/test/integration/index.spec.ts
packages/apps/registry-backend/tsconfig.app.json
packages/libs/registry-sdk/CHANGELOG.md
packages/libs/registry-sdk/package.json
packages/libs/registry-sdk/src/generated/openapi.json
packages/libs/registry-sdk/src/generated/vincentApiClientNode.ts
packages/libs/registry-sdk/src/generated/vincentApiClientReact.ts
packages/libs/registry-sdk/src/lib/openApi/app.ts
packages/libs/registry-sdk/src/lib/schemas/appVersion.ts
pnpm-lock.yaml

- Adds edit appVersionTool endpoint definition to facilitate modification of `hiddenSupportedPolicies`
- Implements missing AppTool management routes along with the new edit route
- Adds an integration test suite to verify that the routes are working as expected
- Added `registry-backend` to `nx release` awareness so we can start generating changelogs for the service from now on, and keep track of deployments by semver
- Fixed missing `bin` entry in the package.json 🤦 🤦‍♂️ 😶‍🌫️ 
- Fixed mismatched `@lit-protocol/flags` version. Syncpack, here we come 💯 🥇 
- Fixed incorrect configuration in tsconfig.app.json -- it wasn't including the featureState.json file 🤦 😓 
- Now using explicit `vincent-registry-sdk@^2.1.0`
Please describe the tests that you ran to verify your changes. Provide …

Registry Backend - Implement missing AppTool functionality

---

typedoc.site.config.js

Remove `customTitle` attribute from `typedoc.site.config.js` so that the title of the docs are no longer `Why Vincent?` and are instead just `Vincent Docs`

fix: remove docs customTitle from `typedoc.site.config.js`

---

package.json
packages/apps/registry-backend/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Added `heroku-postbuild` script to the root `package.json`.  This effectively disables our existing "build _every_ package" build command during Heroku deployment.
- Resolves an OOM error encountering while attempting to build the Dashboard unnecessarily during deployment of the registry-backend to Heroku. We were building the _entire monorepo_ during deployment of our 85kb registry backend ;) We only need to run `pnpm install` and then build _just the registry_.
- I had to pin the registry-sdk version at a specific version that we know is published to NPM for the references to it to resolve with these changes
- I will circle back on that issue later. We have a bit of a conundrum to solve here, in that we _want_ to use `workspace:*` linking in the repo -- but we also want the deployed app …

chore: Disable full repo build during Heroku deployment

---

docs/custom.css

Small bug fix to fix:
now the titles word wrap as the screen gets smaller until it's too small that the sidebar is replaced by a hamburger menu. Now the page looks like:

Fix nav menu item title being truncated when screen size got too small

---

README.md

This PR fixes multiple broken or outdated links in the README file, updating them to point to the correct, current URLs on [https://docs.heyvincent.ai](https://docs.heyvincent.ai).
No code or functionality is changed — only documentation (README).
All the updated links were manually checked in a browser to confirm they point to valid and correct pages.
Steps:
* Opened README in a browser/preview
* Clicked each updated link and verified it leads to the intended documentation page without error
I created a [release plan](https://nx.dev/recipes/nx-release/file-based-versioning-version-plans) (`nx release plan`) describing my changes and the version bump (N/A — docs only)

Update broken documentation links in README

---

packages/libs/app-sdk/src/webAuthClient/internal/uriHelpers.ts

This PR fixes the consent page url built in composeDelegationAuthUrl used in the updated dashboard
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

fix: dashboard consent url in composeDelegationAuthUrl

---

packages/apps/app-dashboard/src/components/developer-dashboard/form-fields/ImageUploadField.tsx
packages/apps/app-dashboard/src/utils/developer-dashboard/imageUtils.ts
packages/apps/registry-backend/src/lib/express/index.ts

A simple change to the registry. This will allow developers to put larger jpg/jpegs/gifs as their app/ability/policy logos, and ensure that the base metadata size never hits the previous 100KB default limit.
Locally on a dev server. I uploaded a 300KB+ GIF as the app logo, which didn't work previously. Now it does.

Bump Express Request Limit to 256KB

---

docs/src/Developers/Abilities/EvmTransactionSigner.md
docs/src/Developers/App-Agent-Developers/Auth-Users.md
docs/src/Developers/App-Agent-Developers/Executing-Abilities.md
docs/src/Developers/App-Agent-Developers/Getting-Started.md
docs/src/Developers/App-Agent-Developers/Upgrading-Apps.md
docs/src/Why-Vincent.md
typedoc.config.base.js

- Replaces link to old DCA example with Vincent Yield Maximizer
- Fixes some warnings when building docs

docs: replace link to dca example with vincent yield

---

.nx/version-plans/version-plan-1755533774990.md
packages/apps/app-dashboard/src/components/user-dashboard/dashboard/UserPermissionPage.tsx
packages/libs/contracts-sdk/jest.config.js
packages/libs/contracts-sdk/src/internal/user/User.ts
packages/libs/contracts-sdk/src/types.ts
packages/libs/contracts-sdk/src/utils/policyParams.ts
packages/libs/contracts-sdk/test/policyParams.spec.ts

- added `deletePolicyIpfsCids` to `setAbilityPolicyParameters()` parameters
Adds functionality to allow contract-sdk consumers to remove existing policy parameters during sparse updates, by providing an optional `deletePolicyIpfsCids` argument to `setAbilityPolicyParameters()`
- Added `deletePolicyIpfsCids` to `setAbilityPolicyParameters()` parameters
- Provide an array of policy IPFS CIDs to remove existing policy parameters for those policies during sparse updates
- Behaviour of `policyParams` remains unchanged
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

feat: Allow deletion of existing policy parameters during sparse updates

---

packages/apps/app-dashboard/src/components/user-dashboard/connect/AppUnavailableConnect.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/ConnectPage.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/ConnectPageWraper.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/DisabledVersionConnect.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/RepermitConnect.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/ActionButtons.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/ui/InfoBanner.tsx
packages/apps/app-dashboard/src/hooks/user-dashboard/useAgentPkpForApp.ts
packages/apps/app-dashboard/src/hooks/user-dashboard/useAllAgentApps.ts
packages/apps/app-dashboard/src/utils/user-dashboard/getAgentPkps.ts

1. User unpermits an app
2. The appId is still tied to their PKP on-chain
3. The user wants to permit the app again
4. **NEW:** The `ConnectPage` screen will now inform them that they've permitted the app previously, and repermitting the app will grant the same permissions that they had previously.
The VY integration is safe, since VY will be added to the `permittedPkps` array, and the detection for `appId` -1 is still functional. 
Locally with manual testing.

feat(dashboard): unpermitted PKP detection + reuse

---

packages/apps/app-dashboard/src/components/user-dashboard/dashboard/UserPermissionPage.tsx

Bug fix. We would submit an empty object when no changes to the exiting policy permissions had been made. The `contracts-sdk` didn't like this, since it doesn't know what to do with an empty object (nothing). 
Added a check on submission, where if nothing in the policies has changed, then nothing happens:
Locally

fix(dashboard): check for policy deletions and updates when permissioning

---

packages/apps/app-dashboard/src/components/user-dashboard/auth/ConnectMethods.tsx
packages/apps/app-dashboard/src/components/user-dashboard/auth/EthWalletAuth.tsx
packages/apps/app-dashboard/src/components/user-dashboard/auth/StytchOTP.tsx
packages/apps/app-dashboard/src/components/user-dashboard/auth/WebAuthn.tsx
packages/apps/app-dashboard/src/components/user-dashboard/connect/Connect.tsx
packages/apps/app-dashboard/src/hooks/user-dashboard/useAuthInfo.ts
packages/apps/app-dashboard/src/hooks/user-dashboard/useAuthenticate.ts

Users ran into an issue when #315 was merged, where their authentication state was broken since we would have part of the authentication information in localstorage (`lit-auth-info`, but not `userPKP`). This would create a race condition with `getValidSessionSigs()`, where we would have authentication information, but we wouldn't be able to generate valid session signatures. This caused the page to then continue, look for session signatures (they don't exist), and then put the users back on the authentication page.
This PR has two fixes:
- Added a conditional to `getValidSessionSigs()` where we only check when we have a `userPKP`. If we don't, it means our stored authentication information is corrupted, and we clear it. This is run immediately after attempting to get valid session …

fix(dashboard): atomic saving of authentication info

---

.nx/version-plans/version-plan-1758245236765.md
packages/libs/contracts-sdk/abis/VincentUserViewFacet.abi.json
packages/libs/contracts-sdk/contracts/VincentDiamond.sol
packages/libs/contracts-sdk/contracts/facets/VincentUserViewFacet.sol
packages/libs/contracts-sdk/script/UpdateFacet.sol
packages/libs/contracts-sdk/src/contractClient.ts
packages/libs/contracts-sdk/src/index.ts
packages/libs/contracts-sdk/src/internal/user/UserView.ts
packages/libs/contracts-sdk/src/internal/user/types.ts
packages/libs/contracts-sdk/src/types.ts
packages/libs/contracts-sdk/test/facets/VincentUserFacet.t.sol
packages/libs/contracts-sdk/test/sdk.spec.ts

Addresses [this issue](https://linear.app/litprotocol/issue/DREL-1092/error-processing-delegated-wks-accs) and implements the proposed solution.
`isDelegateePermitted` takes a Delegatee ETH address, Agent Wallet PKP token ID, and an Ability IPFS CID and returns `bool` for whether or not that Delegatee is permitted to execute the Ability using the PKP
- New assertions calling `isDelegateePermitted` in existing facet Solidity tests
- New test cases added to contract SDK E2E tests

Add new `isDelegateePermitted` function to `VincentUserViewFacet`

---

.nx/version-plans/version-plan-1759560325219.md
packages/libs/contracts-sdk/abis/VincentUserViewFacet.abi.json
packages/libs/contracts-sdk/contracts/facets/VincentUserViewFacet.sol
packages/libs/contracts-sdk/src/internal/user/UserView.ts
packages/libs/contracts-sdk/src/internal/user/types.ts
packages/libs/contracts-sdk/src/types.ts
packages/libs/contracts-sdk/test/facets/VincentAppFacet.t.sol
packages/libs/contracts-sdk/test/sdk.spec.ts

- `getPermittedAppVersionForPkp` no longer reverts if the requested App is deleted (i.e. it will return the permitted version for a deleted App)
- `getAllPermittedAppIdsForPkp` includes the App IDs for deleted Apps (Note: this method is deprecated, but I don't think it makes sense to not update it along with the other getters)
- `getPermittedAppsForPkps` includes deleted Apps in return value with `isDeleted: true` (`false` for non-deleted Apps)
- `getUnpermittedAppsForPkps` includes deleted Apps in return value with `isDeleted: true` (`false` for non-deleted Apps)
- Adds `isDeleted` to return value for Contract SDK wrapper functions
- Added assertions to `packages/libs/contracts-sdk/test/facets/VincentAppFacet.t.sol` to validate new `isDeleted` property
- Added assertions to …

Return deleted Apps for get Apps contract methods
